# Generated by Django 4.2.1 on 2023-06-02 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
