# Generated by Django 4.2.1 on 2023-06-05 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_productimage_is_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_gamer',
            field=models.BooleanField(default=False),
        ),
    ]
