# Generated by Django 4.2.1 on 2023-06-20 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_product_is_gamer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shipping_charge',
        ),
    ]
