# Generated by Django 4.2.1 on 2023-08-13 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_favitem_carditem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CardItem',
            new_name='CartItem',
        ),
    ]
