# Generated by Django 4.2.1 on 2023-08-15 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_order_delivery_man_alter_orderitem_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='dispatched',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='on_the_way',
            field=models.BooleanField(default=False),
        ),
    ]
