# Generated by Django 4.2.1 on 2023-08-16 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_order_dispatched_order_on_the_way'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='useful',
            new_name='is_useful',
        ),
    ]
