# Generated by Django 4.2.1 on 2023-08-25 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_order_paid_alter_order_notes_alter_order_postal_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='title',
            field=models.CharField(default='', max_length=45),
            preserve_default=False,
        ),
    ]
