# Generated by Django 4.2.1 on 2023-08-26 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_coupon_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='postal_code',
        ),
    ]
