# Generated by Django 4.2.1 on 2023-09-11 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_remove_orderitem_customer_order_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='hidden',
            field=models.BooleanField(default=True),
        ),
    ]
