# Generated by Django 4.2.1 on 2023-09-12 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_remove_review_title_alter_customer_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
    ]
