# Generated by Django 4.2.1 on 2023-09-12 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_remove_product_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliveryman',
            old_name='vehicle_capacity',
            new_name='payload',
        ),
    ]
