# Generated by Django 4.2.1 on 2023-09-12 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_rename_vehicle_capacity_deliveryman_payload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='notes',
            field=models.CharField(default='Nothing', max_length=255),
        ),
    ]
