# Generated by Django 4.2.1 on 2023-09-12 09:05

import api.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_alter_order_delivery_man'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='content',
            field=models.CharField(default='', validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(45), api.validators.profanity_filter]),
        ),
    ]
